### Site metadata ###

site_name: bert.self
site_description: Notes from my career in IT thus far
site_url:

repo_url:
edit_uri:
dev_addr: '0.0.0.0:8000'

docs_dir: .
site_dir: site

### global variables ###
extra:
  globals:
    self:
      email: berttejeda@gmail.com

### Build settings ###

theme:
  name: material
  palette:
  - scheme: default
    toggle:
      icon: material/weather-sunny
      name: Switch to light mode
  - scheme: slate
    toggle:
      icon: material/weather-night
      name: Switch to dark mode
  #favicon: img/favicon.ico
  search_index_only: true
  include_search_page: true
  features:
    - search.suggest
    - search.highlight
    #- navigation.sections
    #- content.code.annotate      
  logo: docs/theme/images/logo.jpg
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16  
  font:
      text: Ubuntu
      code: Source Code Pro 

extra_css:
 - docs/theme/css/bootstrap.min.css
 - docs/theme/css/dataTables.bootstrap5.min.css
 - docs/theme/css/codecopy.css
 - docs/theme/js/cheatdata.css

extra_javascript:
 - docs/theme/js/jquery-3.3.1.slim.min.js
 - docs/theme/js/popper.min.js
 - docs/theme/js/jquery.dataTables.min.js
 - docs/theme/js/cheatdata.js
 - docs/theme/js/d3.min.js
 - docs/theme/js/mermaid.min.js
 - docs/theme/js/markmap-lib/index.min.js
 - docs/theme/js/markmap-view/index.min.js

markdown_extensions:
  - attr_list
  - markdown_blockdiag:
      format: svg  
  - codehilite
  - footnotes
  - lightgallery
  - markdown_include.include:
      base_path: .
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true  
  - pymdownx.snippets:
      base_path: docs  
  - pymdownx.superfences:
      custom_fences:
        - name: pymdownx
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format  
        - name: mermaid # Take the fenced parts marked with mermaid
          class: mermaid # Turn them into class='mermaid'.
          format: !!python/name:mermaid2.fence_mermaid # To format those pieces, 
                                                       # use the function fence_mermaid, 
                                                       # from the mermaid2 package.
  - toc:
      permalink: true

plugins:
  - diagrams
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.11.6
      view_version: 0.2.6    
  - mermaid2
  - macros:
      module_name: docs/macros
      include_dir: .
  - same-dir
  - search:
      lang: ["en"]
      prebuild_index: false
      
nav:
   - Home: README.md
   # - Automation:
   #    - bash: docs/topics/automation/bash.md
   #    - python: docs/topics/automation/python.md
   - Ansible:
      - lessons:
        - lesson-01: docs/topics/ansible/lesson-01/lesson.md
      - windows: 
        - Portable Ansible Installation on Windows 7 using Cygwin: docs/topics/ansible/windows/ansible-on-windows-7-with-cygwin.md
   - Docker:
      - lessons:
        - lesson-01: docs/topics/docker/lesson-01/lesson.md    
        - lesson-02: docs/topics/docker/lesson-02/lesson.md    
        - lesson-03: docs/topics/docker/lesson-03/lesson.md    
        - lesson-04: docs/topics/docker/lesson-04/lesson.md
   - Crossplane:
      - lessons:
        - lesson-01: docs/topics/crossplane/lesson-01/lesson.md
        - lesson-02: docs/topics/crossplane/lesson-02/lesson.md
   - Kubernetes:
      - lessons:
        - lesson-01: docs/topics/kubernetes/lesson-01/lesson.md
        - lesson-02: docs/topics/kubernetes/lesson-02/lesson.md        
      - troubleshooting: 
        - Docker Volume Mounts And Autofs: docs/topics/kubernetes/troubleshooting/docker-volume-mounts-and-autofs.md
        - Pod Tolerates Node Taints: docs/topics/kubernetes/troubleshooting/pod_tolerates_node_taints.md
   - pfSense:
      - troubleshooting: 
        - Boot failure after upgrading pfsense to 2.4.0: docs/topics/pfsense/troubleshooting/boot-failure-after-upgrade-to-2-4-0.md
   - Terraform:
      - lessons:
        - lesson-01: docs/topics/terraform/lesson-01/lesson.md    
   - About MkDocs:
      - Overview: docs/about-mkdocs.md
      - Quickstart: docs/tutorial/quickstart.md
      - TL;DR: docs/tutorial/tldr.md
      - Installation: docs/tutorial/installation.md
      - Set up project: docs/tutorial/setup-project.md
      - Advanced: docs/tutorial/advanced.md
      - Usage: docs/tutorial/usage.md
      - Deploy: docs/tutorial/deploy.md